name: Build PCSX2‑Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE: app

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pcsx2-android-debug
        path: ${{ env.MODULE }}/build/outputs/apk/debug/*.apk

    - name: Upload release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pcsx2-android-release
        path: ${{ env.MODULE }}/build/outputs/apk/release/*.apk